### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by 2bbe** [puttyman/hass-amplifi#20]
Hi
I Get the following error continuously in the log: 

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/amplifi/coordinator.py:80 
Integration: Amplifi (documentation, issues) 
First occurred: 07:41:29 (43 occurrences) 
Last logged: 07:48:29

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/config/custom_components/amplifi/coordinator.py", line 80, in extract_ethernet_ports
    self._ethernet_ports = self.data[ETHERNET_PORTS_IDX][router_mac_addr]
KeyError: '74:83:c2:xx:xx:xx'
`
Any idea what’s wrong?

**Comment by ciryon** [comment]
I get the same error too, no clue what it means.

**Comment by hawksj** [comment]
Not reproduceable in my instance, as this issue is over 1.5 years old and there have been multiple new versions since opening, I will close as stale but please reopen or create a duplicate issue if this error still occurs.
