### ISSUE TITLE
session closed error

### ISSUE THREAD

**Issue by glugg** [puttyman/hass-amplifi#22]
I get this error shortly after adding the integration and all related entities gets unavailable.

Logger: custom_components.amplifi.coordinator
Source: custom_components/amplifi/client.py:81
Integration: Amplifi (documentation, issues)
First occurred: 08:32:36 (21 occurrences)
Last logged: 08:35:56

Unexpected error fetching amplifi data: Session is closed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/amplifi/coordinator.py", line 55, in _async_update_data
    devices = await self._client.async_get_devices()
  File "/config/custom_components/amplifi/client.py", line 26, in async_get_devices
    return await self._async_get_info()
  File "/config/custom_components/amplifi/client.py", line 81, in _async_get_info
    resp = await self._client.post(info_async_url, data=form_data)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 399, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Comment by glugg** [comment]
Had been trying a couple of times reinstalling the integration and rebooting but same error. But of course after posting my issue here and then reinstalling once again it works.
